name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      # Yarn dependencies
      - name: Yarn Install
        run: yarn install

      # Lint
      - name: Lint
        run: yarn run lint
